(defun (setf mine-index) (value board i)
  (setf (car (aref board i)) value))
(defun mine-index (board i)
  (car (aref board i)))

(defun new-board (n m num xy)
  (let* ((nm (* n m))
         (listboard (loop repeat nm collect (list 0 0)))
         (board (do ((i 0)
                     (board (make-array nm :initial-contents listboard))
                     (rand (random nm) (random nm)))
                    ((>= i num) board)
                    (unless (or (= rand xy)
                                (= (mine-index board rand) 9))
                      (incf i)
                      (setf (mine-index board rand) 9)))))
    (list n m num board)))
